name: Python
on: [push, pull_request]

jobs:
  test:
    name: Python 3.6
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r dev-requirements.txt
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        cd tests
        pytest --emoji